version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"

  spark-submitter:
    build:
      context: ./phase_2_simple_etl
      dockerfile: Dockerfile
    container_name: spark-submitter
    depends_on:
      - elasticsearch
      - minio
    command: ["/opt/bitnami/spark/bin/spark-submit", "--master", "local[*]", "--packages", "org.elasticsearch:elasticsearch-spark-30_2.12:8.4.3", "/opt/bitnami/spark/work-dir/main.py"]
