version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"

  spark-iceberg-nessie:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg-nessie
    depends_on:
      - nessie
      - minio
      - elasticsearch
    volumes:
      - ./notebooks:/home/iceberg/notebooks
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - SPARK_HOME=/opt/spark
      - SPARK_MASTER_HOST=spark-iceberg-nessie
    command: >
      /opt/spark/bin/pyspark
      --master local[*]
      --packages org.elasticsearch:elasticsearch-spark-30_2.12:8.4.3
      --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
      --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1
      --conf spark.sql.catalog.nessie.ref=main
      --conf spark.sql.catalog.nessie.authentication.type=NONE
      --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog
      --conf spark.sql.catalog.nessie.warehouse=s3a://warehouse
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
      --conf spark.hadoop.fs.s3a.access.key=admin
      --conf spark.hadoop.fs.s3a.secret.key=password
      --conf spark.hadoop.fs.s3a.path.style.access=true
      --conf spark.driver.memory=2g
