version: '3.7'

networks:
  iceberg-net:
    external: true

services:
  spark-submitter:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/opt/bitnami/spark/bin/spark-submit", "--master", "local[*]", "--packages", "org.elasticsearch:elasticsearch-spark-30_2.12:8.4.3", "/opt/bitnami/spark/work-dir/main.py"]
    networks:
      - iceberg-net