version: '3'

networks:
  iceberg-net:
    external: true

services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - .:/opt/spark/work-dir
    environment:
      - SPARK_MODE=master
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    networks:
      - iceberg-net

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/spark/work-dir
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    networks:
      - iceberg-net
